
server:
  port: 8888
spring:
  application:
    name: pago_servicios_configserver

  cloud:
    config:
      server:
        git:
          uri: https://github.com/cesarac561/pago_servicios_repoconfig.git
          default-label: main
          timeout: 10
